name: webapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.5.0
  stacked_services: ^1.6.0
  flutter_screenutil: ^5.9.3
  navigation_rail_flutter: ^1.0.3
  fl_chart: ^1.1.1
  data_table_2: ^2.7.2
  image_picker: ^1.2.1
  file_picker: ^10.3.7
  go_router: ^17.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.3
  dropdown_search: ^6.0.2



dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

  fonts:
   - family: Inter_Bold
     fonts:
       - asset: assets/fonts/Inter_Bold.ttf
   - family: Inter_Medium
     fonts:
       - asset: assets/fonts/Inter_Medium.ttf
   - family: Inter_Regular
     fonts:
       - asset: assets/fonts/Inter_Regular.ttf
   - family: Inter_SemiBold
     fonts:
       - asset: assets/fonts/Inter_SemiBold.ttf

  assets:
    - assets/images/
    - assets/json/cities.json

